# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ceb7c64e6dc5bd43f31b19dd22ccec510310429fd527ed9310132eb7fdcf8e5bb67001dd4cc47268ec5960b3640add70c3783df911bd0c7db4995f5927967f

test:
  secret_key_base: 0e5c717cba8d0bf7d1e900f3c2983242e26902f4d7a49b74a17feba13a25d5e8bd73fad3c8e798f9c254538a92d48b3da593c3af172ea8338afcc389747bee3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
